### ISSUE TITLE
Which tool to use  or how to do End-To-End Testing from front till backend.

### ISSUE THREAD

**Issue by alokpandeyrc** [andreschaffer/microservices-testing-examples#3]

**Comment by andreschaffer** [comment]
Hi, you can do contract testing between frontend and backend the same way. Take a look at Pact JS.

**Comment by alokpandeyrc** [comment]
Hi Andreschaffer,
Nice to hear from you. Actually i am using Pact-JVM . I beleive if you are doing testing for front and back in microservices constitute the same thing...right?  The request and response is the same i beleive....

**Comment by andreschaffer** [comment]
Hmm I'm not entirely sure I understand the question, but yes, the approach should be the same.
