### ISSUE TITLE
is rest-assured suitable for microservices testing ?

### ISSUE THREAD

**Issue by vikramvi** [andreschaffer/microservices-testing-examples#4]
Hi,

wrt your article https://labs.spotify.com/2018/01/11/testing-of-microservices/

can you please clarify if `rest-assured` can be used in this case ?

I'm using this library to test end points / microservices since last few years and would like to know how it fits in your scenario ?

Thanks & Regards,
Vikram

**Comment by andreschaffer** [comment]
Hi Vikram,
Absolutely. You can use rest-assured to test / verify the behaviour of your service.
To make sure that you don't accidentally break the contracts between services, you can then use a 'consumer-driven contract based testing' tool (e.g. Pact).

**Comment by vikramvi** [comment]
Thanks for answer.

https://docs.pact.io/ is the tool you're talking about ?

**Comment by andreschaffer** [comment]
Exactly! 
There are others also: https://cloud.spring.io/spring-cloud-contract/ and http://thoughtworks.github.io/pacto/
